let fs = require("fs");

let nonEssentials = [
  "cast.expr.ts",
  "keyword.control.as.ts",
  "keyword.control.at-rule.import",
  "keyword.control.default",
  "keyword.control.export",
  "keyword.control.from",
  "keyword.control.import",
  "keyword.operator.expression.is",
  "keyword.operator.type.annotation.ts",
  "keyword.operator.new",
  "meta.return.type.arrow.ts",
  "meta.return.type.ts",
  "meta.type.annotation",
  "meta.type.function.ts",
  "meta.type.function.ts",
  "meta.type.parameters.ts",
  "meta.var.expr",
  "punctuation.terminator.rule",
  "punctuation.terminator.statement",
  // Includes: `boolean`, `any`, `string`...
  "support.type.primitive.ts"
];

let literals = [
  // Includes booleans, null and undefined
  "constant.language",
  "constant.numeric",
  "string.quoted",
  "string.regexp",
  "string.template",
  "meta.array.literal",
  "meta.objectliteral"
];

let operators = [
  "keyword.operator.arithmetic",
  "keyword.operator.assignment",
  "keyword.operator.comparison",
  "keyword.operator.expression",
  "keyword.operator.increment",
  "keyword.operator.list",
  "keyword.operator.logical",
  "keyword.operator.pipe",
  "keyword.operator.relational",
  "keyword.operator.spread",
  "keyword.operator.ternary"
];

let functions = ["meta.function-call", "new.expr", "support.function"];

let attentionSeekers = [
  "comment",
  "keyword.other.debugger",
  "keyword.other.important",
  "variable.language.this",
  "variable.other.jsdoc"
];

/**
 * Tokens that somehow have been overridden by other settings and therefore
 * need to reset.
 */
let defaults = [
  "constant.language.import-export-all",
  "entity.name.function.tagged-template",
  "meta.function-call.arguments",
  "keyword.control.flow",
  "keyword.control.loop",
  "meta.arrow",
  "meta.brace.round",
  "meta.definition.variable",
  "meta.function.expression",
  "meta.object-literal.key",
  "meta.parameters",
  "meta.template.expression",
  "punctuation.accessor",
  "punctuation.separator.comma",
  "support.class",
  "support.constant",
  "support.type.property-name.css",
  "support.variable",
  "variable.language.arguments",
  "variable.other.constant.property",
  "variable.other.constant",
  "variable.other.object",
  "variable.other.property",
  "variable.other.readwrite"
];

let tokenColor = color => token => ({
  scope: token,
  settings: {
    foreground: color
  }
});

let nonEssentialColor = "#696d77";
let defaultColor = "#eaf2f1";
// let functionColor = "#9cd1bb";
let functionColor = "#bad761";
let literalColor = "#ffd76d";
let operatorColor = "#ff657a";
let attentionColor = "#ff657a";
// let attentionColor = "#c39ac9";

let theme = {
  name: "Opaline Dark",
  type: "dark",
  colors: {
    focusBorder: "#696d77",
    foreground: "#eaf2f1",
    "widget.shadow": "#161821",
    "selection.background": "#b2b9bd26",
    descriptionForeground: "#888d94",
    errorForeground: "#ff657a",
    "textBlockQuote.background": "#3a3d4b",
    "textBlockQuote.border": "#3a3d4b",
    "textCodeBlock.background": "#3a3d4b",
    "textLink.activeForeground": "#eaf2f1",
    "textLink.foreground": "#ffd76d",
    "textPreformat.foreground": "#eaf2f1",
    "textSeparator.foreground": "#696d77",
    "button.background": "#3a3d4b",
    "button.foreground": "#888d94",
    "button.hoverBackground": "#282a3a",
    "dropdown.background": "#282a3a",
    "dropdown.listBackground": "#3a3d4b",
    "dropdown.border": "#282a3a",
    "dropdown.foreground": "#888d94",
    "input.background": "#3a3d4b",
    "input.border": "#3a3d4b",
    "input.foreground": "#eaf2f1",
    "input.placeholderForeground": "#696d77",
    "inputOption.activeBackground": "#535763",
    "inputOption.activeBorder": "#535763",
    "inputValidation.errorBackground": "#3a3d4b",
    "inputValidation.errorForeground": "#ff657a",
    "inputValidation.errorBorder": "#ff657a",
    "inputValidation.infoBackground": "#3a3d4b",
    "inputValidation.infoForeground": "#9cd1bb",
    "inputValidation.infoBorder": "#9cd1bb",
    "inputValidation.warningBackground": "#3a3d4b",
    "inputValidation.warningForeground": "#ff9b5e",
    "inputValidation.warningBorder": "#ff9b5e",
    "scrollbar.shadow": "#282a3a",
    "scrollbarSlider.activeBackground": "#eaf2f112",
    "scrollbarSlider.background": "#eaf2f112",
    "scrollbarSlider.hoverBackground": "#eaf2f112",
    "badge.foreground": "#282a3a",
    "badge.background": "#ffd76d",
    "progressBar.background": "#3a3d4b",
    "list.activeSelectionBackground": "#282a3a",
    "list.activeSelectionForeground": "#ffd76d",
    "list.errorForeground": "#ff657a",
    "list.warningForeground": "#ff9b5e",
    "list.dropBackground": "#1e1f2bbf",
    "list.focusBackground": "#282a3a",
    "list.focusForeground": "#eaf2f1",
    "list.highlightForeground": "#eaf2f1",
    "list.hoverBackground": "#1e1f2b",
    "list.hoverForeground": "#eaf2f1",
    "list.inactiveSelectionBackground": "#282a3a",
    "list.inactiveSelectionForeground": "#ffd76d",
    "list.inactiveFocusBackground": "#282a3a",
    "list.invalidItemForeground": "#ff657a",
    "listFilterWidget.background": "#282a3a",
    "listFilterWidget.outline": "#282a3a",
    "listFilterWidget.noMatchesOutline": "#ff657a",
    "activityBar.background": "#161821",
    "activityBar.dropBackground": "#1e1f2bbf",
    "activityBar.foreground": "#b2b9bd",
    "activityBar.inactiveForeground": "#535763",
    "activityBar.border": "#161821",
    "activityBarBadge.background": "#ffd76d",
    "activityBarBadge.foreground": "#282a3a",
    "breadcrumb.foreground": "#888d94",
    "breadcrumb.focusForeground": "#b2b9bd",
    "breadcrumb.activeSelectionForeground": "#eaf2f1",
    "settings.headerForeground": "#ffd76d",
    "settings.dropdownBackground": "#3a3d4b",
    "settings.dropdownForeground": "#eaf2f1",
    "settings.dropdownBorder": "#3a3d4b",
    "settings.dropdownListBorder": "#888d94",
    "settings.modifiedItemIndicator": "#ffd76d",
    "settings.checkboxBackground": "#3a3d4b",
    "settings.checkboxForeground": "#eaf2f1",
    "settings.checkboxBorder": "#3a3d4b",
    "settings.textInputBackground": "#3a3d4b",
    "settings.textInputForeground": "#eaf2f1",
    "settings.textInputBorder": "#3a3d4b",
    "settings.numberInputBackground": "#3a3d4b",
    "settings.numberInputForeground": "#eaf2f1",
    "settings.numberInputBorder": "#3a3d4b",
    "sideBar.background": "#1e1f2b",
    "sideBar.foreground": "#888d94",
    "sideBar.border": "#161821",
    "sideBar.dropBackground": "#1e1f2bbf",
    "sideBarTitle.foreground": "#535763",
    "sideBarSectionHeader.background": "#1e1f2b",
    "sideBarSectionHeader.foreground": "#696d77",
    "editorGroup.emptyBackground": "#161821",
    "editorGroup.focusedEmptyBorder": "#1e1f2b",
    "editorGroup.border": "#1e1f2b",
    "editorGroup.dropBackground": "#1e1f2bbf",
    "editorGroupHeader.noTabsBackground": "#282a3a",
    "editorGroupHeader.tabsBackground": "#282a3a",
    "editorGroupHeader.tabsBorder": "#282a3a",
    "editorPane.background": "#282a3a",
    "tab.activeBackground": "#282a3a",
    "tab.activeForeground": "#ffd76d",
    "tab.border": "#282a3a",
    "tab.activeBorder": "#ffd76d",
    "tab.unfocusedActiveBorder": "#888d94",
    "tab.inactiveBackground": "#282a3a",
    "tab.inactiveForeground": "#888d94",
    "tab.unfocusedActiveForeground": "#b2b9bd",
    "tab.unfocusedInactiveForeground": "#888d94",
    "tab.hoverBackground": "#282a3a",
    "tab.unfocusedHoverBackground": "#282a3a",
    "tab.hoverBorder": "#535763",
    "tab.unfocusedHoverBorder": "#282a3a",
    "tab.activeModifiedBorder": "#535763",
    "tab.inactiveModifiedBorder": "#535763",
    "tab.unfocusedActiveModifiedBorder": "#3a3d4b",
    "tab.unfocusedInactiveModifiedBorder": "#3a3d4b",
    "editor.background": "#282a3a",
    "editor.foreground": "#eaf2f1",
    "editorLineNumber.foreground": "#535763",
    "editorLineNumber.activeForeground": "#b2b9bd",
    "editorCursor.background": "#282a3a",
    "editorCursor.foreground": "#eaf2f1",
    "editor.selectionBackground": "#b2b9bd26",
    "editor.inactiveSelectionBackground": "#eaf2f10c",
    "editor.selectionHighlightBackground": "#eaf2f126",
    "editor.selectionHighlightBorder": "#00000000",
    "editor.wordHighlightBackground": "#eaf2f126",
    "editor.wordHighlightBorder": "#00000000",
    "editor.wordHighlightStrongBackground": "#eaf2f126",
    "editor.wordHighlightStrongBorder": "#00000000",
    "editor.findMatchBackground": "#eaf2f126",
    "editor.findMatchBorder": "#ffd76d",
    "editor.findMatchHighlightBackground": "#eaf2f126",
    "editor.findMatchHighlightBorder": "#00000000",
    "editor.findRangeHighlightBackground": "#eaf2f10c",
    "editor.findRangeHighlightBorder": "#00000000",
    "editor.hoverHighlightBackground": "#eaf2f10c",
    "editor.lineHighlightBackground": "#eaf2f10c",
    "editor.lineHighlightBorder": "#00000000",
    "editorLink.activeForeground": "#9cd1bb",
    "editor.rangeHighlightBackground": "#3a3d4b",
    "editor.rangeHighlightBorder": "#3a3d4b",
    "editorWhitespace.foreground": "#535763",
    "editorIndentGuide.background": "#3a3d4b",
    "editorRuler.foreground": "#535763",
    "editorCodeLens.foreground": "#696d77",
    "editorBracketMatch.background": "#282a3a",
    "editorBracketMatch.border": "#696d77",
    "editorError.foreground": "#ff657a",
    "editorError.border": "#00000000",
    "editorWarning.foreground": "#ff9b5e",
    "editorWarning.border": "#00000000",
    "editorInfo.foreground": "#9cd1bb",
    "editorInfo.border": "#282a3a",
    "editorHint.foreground": "#c39ac9",
    "editorHint.border": "#282a3a",
    "editorGutter.background": "#282a3a",
    "editorGutter.modifiedBackground": "#ff9b5e",
    "editorGutter.addedBackground": "#bad761",
    "editorGutter.deletedBackground": "#ff657a",
    "diffEditor.insertedTextBackground": "#bad76119",
    "diffEditor.insertedTextBorder": "#00000000",
    "diffEditor.removedTextBackground": "#ff657a19",
    "diffEditor.removedTextBorder": "#00000000",
    "editorWidget.background": "#3a3d4b",
    "editorWidget.border": "#3a3d4b",
    "editorSuggestWidget.background": "#3a3d4b",
    "editorSuggestWidget.border": "#3a3d4b",
    "editorSuggestWidget.foreground": "#b2b9bd",
    "editorSuggestWidget.highlightForeground": "#eaf2f1",
    "editorSuggestWidget.selectedBackground": "#696d77",
    "editorHoverWidget.background": "#3a3d4b",
    "editorHoverWidget.border": "#282a3a",
    "debugExceptionWidget.background": "#3a3d4b",
    "debugExceptionWidget.border": "#282a3a",
    "editorMarkerNavigation.background": "#3a3d4b",
    "editorMarkerNavigationError.background": "#ff657a",
    "editorMarkerNavigationWarning.background": "#ff9b5e",
    "editorMarkerNavigationInfo.background": "#9cd1bb",
    "peekView.border": "#282a3a",
    "peekViewEditor.background": "#3a3d4b",
    "peekViewEditorGutter.background": "#3a3d4b",
    "peekViewEditor.matchHighlightBackground": "#535763",
    "peekViewResult.background": "#3a3d4b",
    "peekViewResult.fileForeground": "#888d94",
    "peekViewResult.lineForeground": "#888d94",
    "peekViewResult.matchHighlightBackground": "#535763",
    "peekViewResult.selectionBackground": "#3a3d4b",
    "peekViewResult.selectionForeground": "#eaf2f1",
    "peekViewTitle.background": "#3a3d4b",
    "peekViewTitleDescription.foreground": "#888d94",
    "peekViewTitleLabel.foreground": "#eaf2f1",
    "merge.currentHeaderBackground": "#ff657a26",
    "merge.currentContentBackground": "#ff657a19",
    "merge.incomingHeaderBackground": "#bad76126",
    "merge.incomingContentBackground": "#bad76119",
    "merge.border": "#282a3a",
    "merge.commonHeaderBackground": "#eaf2f126",
    "merge.commonContentBackground": "#eaf2f119",
    "editorOverviewRuler.border": "#282a3a",
    "editorOverviewRuler.currentContentForeground": "#3a3d4b",
    "editorOverviewRuler.incomingContentForeground": "#3a3d4b",
    "editorOverviewRuler.findMatchForeground": "#eaf2f126",
    "editorOverviewRuler.rangeHighlightForeground": "#eaf2f126",
    "editorOverviewRuler.selectionHighlightForeground": "#eaf2f126",
    "editorOverviewRuler.wordHighlightForeground": "#eaf2f126",
    "editorOverviewRuler.wordHighlightStrongForeground": "#eaf2f126",
    "editorOverviewRuler.modifiedForeground": "#ff9b5e",
    "editorOverviewRuler.addedForeground": "#bad761",
    "editorOverviewRuler.deletedForeground": "#ff657a",
    "editorOverviewRuler.errorForeground": "#ff657a",
    "editorOverviewRuler.warningForeground": "#ff9b5e",
    "editorOverviewRuler.infoForeground": "#9cd1bb",
    "panel.background": "#3a3d4b",
    "panel.border": "#282a3a",
    "panel.dropBackground": "#1e1f2bbf",
    "panelTitle.activeBorder": "#ffd76d",
    "panelTitle.activeForeground": "#ffd76d",
    "panelTitle.inactiveForeground": "#888d94",
    "statusBar.background": "#1e1f2b",
    "statusBar.foreground": "#696d77",
    "statusBar.debuggingBackground": "#696d77",
    "statusBar.debuggingForeground": "#eaf2f1",
    "statusBar.debuggingBorder": "#1e1f2b",
    "statusBar.noFolderBackground": "#1e1f2b",
    "statusBar.noFolderForeground": "#696d77",
    "statusBar.noFolderBorder": "#161821",
    "statusBarItem.activeBackground": "#282a3a",
    "statusBarItem.hoverBackground": "#282a3a",
    "statusBarItem.prominentBackground": "#3a3d4b",
    "statusBarItem.prominentHoverBackground": "#3a3d4b",
    "statusBar.border": "#161821",
    "titleBar.activeBackground": "#1e1f2b",
    "titleBar.activeForeground": "#888d94",
    "titleBar.inactiveBackground": "#1e1f2b",
    "titleBar.inactiveForeground": "#535763",
    "titleBar.border": "#161821",
    "notificationCenter.border": "#3a3d4b",
    "notificationCenterHeader.foreground": "#888d94",
    "notificationCenterHeader.background": "#3a3d4b",
    "notificationToast.border": "#3a3d4b",
    "notifications.foreground": "#b2b9bd",
    "notifications.background": "#3a3d4b",
    "notifications.border": "#3a3d4b",
    "notificationLink.foreground": "#ffd76d",
    "extensionButton.prominentForeground": "#eaf2f1",
    "extensionButton.prominentBackground": "#3a3d4b",
    "extensionButton.prominentHoverBackground": "#535763",
    "pickerGroup.border": "#282a3a",
    "pickerGroup.foreground": "#535763",
    "terminal.background": "#3a3d4b",
    "terminal.foreground": "#eaf2f1",
    "terminal.ansiBlack": "#3a3d4b",
    "terminal.ansiBlue": "#ff9b5e",
    "terminal.ansiBrightBlack": "#696d77",
    "terminal.ansiBrightBlue": "#ff9b5e",
    "terminal.ansiBrightCyan": "#9cd1bb",
    "terminal.ansiBrightGreen": "#bad761",
    "terminal.ansiBrightMagenta": "#c39ac9",
    "terminal.ansiBrightRed": "#ff657a",
    "terminal.ansiBrightWhite": "#eaf2f1",
    "terminal.ansiBrightYellow": "#ffd76d",
    "terminal.ansiCyan": "#9cd1bb",
    "terminal.ansiGreen": "#bad761",
    "terminal.ansiMagenta": "#c39ac9",
    "terminal.ansiRed": "#ff657a",
    "terminal.ansiWhite": "#eaf2f1",
    "terminal.ansiYellow": "#ffd76d",
    "terminal.selectionBackground": "#eaf2f126",
    "terminalCursor.background": "#00000000",
    "terminalCursor.foreground": "#eaf2f1",
    "debugToolBar.background": "#3a3d4b",
    "welcomePage.buttonBackground": "#3a3d4b",
    "welcomePage.buttonHoverBackground": "#535763",
    "walkThrough.embeddedEditorBackground": "#1e1f2b",
    "gitDecoration.modifiedResourceForeground": "#bad761",
    "gitDecoration.deletedResourceForeground": "#ff657a",
    "gitDecoration.untrackedResourceForeground": "#ff9b5e",
    "gitDecoration.ignoredResourceForeground": "#535763",
    "gitDecoration.conflictingResourceForeground": "#ff9b5e"
  },
  tokenColors: [
    ...nonEssentials.map(tokenColor(nonEssentialColor)),
    ...literals.map(tokenColor(literalColor)),
    ...attentionSeekers.map(tokenColor(attentionColor)),
    ...operators.map(tokenColor(operatorColor)),
    ...functions.map(tokenColor(functionColor)),
    ...defaults.map(tokenColor(defaultColor))
  ]
};

fs.writeFileSync(
  "./themes/opaline-dark-color-theme.json",
  JSON.stringify(theme, null, 2),
  "utf-8"
);
